# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='anonymous', max_length=15),
            preserve_default=False,
        ),
    ]
